### ISSUE TITLE
Job bonus payment doesn't work.

### ISSUE THREAD

**Issue by GamingCoookie** [Patrick-van-Halm/dv-jobs_realism-mod#8]
In Job_GetBonusPaymentForTheJob_Patch.cs the if statement should look like this:

`if (!Main.enabled || Main.settings.bonusPaymentEnabled)`
instead of
`if (!Main.enabled && Main.settings.bonusPaymentEnabled)`

**Comment by Patrick-van-Halm** [comment]
Fixed thanks
